name: Artifacts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  artifact:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # installing Node
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          # this will use the latest Node 16 version
          node-version: 16.x
      # install dependencies using clean install to avoid package lock updates
      - run: npm ci
      - run: cp .env.example .env
      - run: npm run build
      - run: npm run tool:attr
      - run: npm run tool:image
      - run: npm run tool:ipfs
      - name: Archive contract ABI
        uses: actions/upload-artifact@v3
        with:
          name: ABI
          path: |
            artifacts
      - name: Archive NFT metadata attributes
        uses: actions/upload-artifact@v3
        with:
          name: Metadata
          path: |
            scripts/tools/attributes/output
            !scripts/tools/attributes/output/.gitignore
      - name: Archive images
        uses: actions/upload-artifact@v3
        with:
          name: Images
          path: |
            scripts/tools/images/output
            !scripts/tools/images/output/.gitignore
      - name: Archive Token URIs
        uses: actions/upload-artifact@v3
        with:
          name: TokenURIs
          path: |
            scripts/tools/ipfs/output
            !scripts/tools/ipfs/output/.gitignore
